---

- name: Ensure OpenSSl and libssl are the latest versions
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: '{{ update_apt_cache }}'
  vars:
    packages:
      - openssl
      - libssl-dev
      - libssl-doc
  tags: packages

- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: '{{ update_apt_cache }}'
  vars:
    packages:
      - build-essential
      - git
      - gettext
      - libxml2-dev
      - libxslt1-dev
      - python-dev
      - python-pip
      - python-pycurl
      - supervisor
      - vim
  tags: packages

- name: Install image libaries for Pillow
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: '{{ update_apt_cache }}'
  vars:
    packages:
      - libjpeg62
      - libjpeg-dev
      - libfreetype6
      - libfreetype6-dev
      - zlib1g-dev
  tags: packages

- name: upgrade pip
  pip:
    name: pip==9.0.3
  tags: packages

- name: Install virtualenv
  pip:
    name: virtualenv
  tags: packages

- name: Create the application user
  when: set_up_application_user
  user: name={{ application_user }} state=present shell="/bin/bash"

- name: Create the application group
  group: name={{ application_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ application_user }} group={{ application_group }} state=present
